name: Android CI/CD Firebase Distribution

on:
  pull_request:
    branches: ["master"]
    types: [closed]

jobs:
  build:
    name: Build & Distribute APK
    if: github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'master' &&
      github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Grant permission for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Decode keystore
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      # 5. Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test

      # 6. Build APK (Prod)
      - name: Build prodRelease APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew :app:assembleProdRelease

      # 7. Find APK
      - name: Find APK filename
        id: apk
        run: echo "APK_PATH=$(ls app/build/outputs/apk/prod/release/app-*.apk)" >> $GITHUB_ENV

      # 8. Upload artifact
      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: APK-${{ github.sha }}
          path: ${{ env.APK_PATH }}

      # 9. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 10. Debug Token (Optional — hapus jika sudah yakin)
      - name: Check Firebase Token Exists
        shell: bash
        run: |
          if [ -z "$FIREBASE_TOKEN" ]; then
            echo "❌ Firebase Token is EMPTY!"
            exit 1
          else
            echo "✔ Firebase Token is PRESENT"
          fi
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # 11. Upload to Firebase Distribution
      - name: Upload to Firebase Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          CI: true
        run: |
          firebase appdistribution:distribute ${{ env.APK_PATH }} \
            --app "$FIREBASE_APP_ID" \
            --token "$FIREBASE_TOKEN" \
            --release-notes "Auto build from CI/CD (merge development -> master)" \
            --testers "pascaladitia@gmail.com" \
            --project my-ecommerce-8405d
